import type { Metadata } from "next";
import ReduxWrapper from "../../redux/ReduxWrapper";
import "./globals.css";
import ProviderWrapper from "./ProviderWrapper";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxWrapper>
      <html lang="en" className={inter.className}>
        <body>
          <ProviderWrapper>{children}</ProviderWrapper>
        </body>
      </html>
    </ReduxWrapper>
  );
}
