import type { Metadata } from "next";
import "./globals.css";
import ReduxWrapper from "../../redux/ReduxWrapper";
import { SnackbarProvider } from "notistack";
import ProviderWrapper from "./ProviderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxWrapper>
      <html lang="en">
        <body>
          <ProviderWrapper>{children}</ProviderWrapper>
        </body>
      </html>
    </ReduxWrapper>
  );
}
